export {default as LandingPage} from "./LandingPage/LandingPage.jsx"
export {default as FormPage} from "./FormPage/FormPage.jsx"
export {default as ResultPage} from "./ResultPage/ResultPage.jsx"
export {default as QuizPage} from "./QuizPage/QuizPage.jsx"
export {default as RegisterPage} from "./RegisterPage/RegisterPage.jsx"